# Generated by Django 3.2 on 2024-02-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvitae', '0003_auto_20240212_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional_member',
            old_name='department',
            new_name='degree_certificate',
        ),
    ]
