# Generated by Django 3.2 on 2024-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvitae', '0004_rename_department_professional_member_degree_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=300)),
            ],
        ),
    ]
