# Generated by Django 3.2 on 2024-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvitae', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolioimage/')),
            ],
        ),
    ]
