# Generated by Django 3.2.1 on 2024-02-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvitae', '0006_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolioimage/'),
        ),
        migrations.AlterField(
            model_name='profileupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage/'),
        ),
    ]
