# Generated by Django 3.2 on 2024-02-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvitae', '0008_auto_20240221_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolioimages/'),
        ),
    ]
