# Generated by Django 3.2 on 2024-02-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvitae', '0009_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=2, upload_to='portfolioimages/'),
            preserve_default=False,
        ),
    ]
